twig:
    default_path: '%kernel.project_dir%/templates'
    # Theme bootstrap pour bien personnaliser les formulaires
    # form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        stripe_public_key_test: '%env(STRIPE_PUBLIC_KEY_TEST)%'
        stripe_public_key_live: '%env(STRIPE_PUBLIC_KEY_LIVE)%'
        

